# Generated by Django 2.2.5 on 2019-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_deal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='currency_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
